version: '3'

services:
  pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bitfly_db
      - POSTGRES_USER=bitfly
      - POSTGRES_PASSWORD=bitfly@123!