version: '3.0'

services:

  pg:
    container_name: bitfly_db
    image: bitnami/postgresql
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: bitfly_api
    image: eliezercastro/bit-fly.co:latest
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - pg

  nginx:
    container_name: bitfly_nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  pgdata: {}
