version: '3.0'

services:
  nginx:
    image: nginx:latest
    container_name: bitfly_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - bitfly-network

  api:
    container_name: bitfly_api
    image: eliezercastro/bit-fly.co:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - pg
    networks:
      - bitfly-network

  pg:
    container_name: bitfly_db
    image: bitnami/postgresql
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bitfly-network

volumes:
  pgdata: {}

networks:
  bitfly-network:
    driver: bridge
