version: '3.0'

services:
  api:
    container_name: bitfly_api
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: eliezercastro/bit-fly.co:latest
    restart: always
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - pg
  pg:
    container_name: bitfly_db
    image: bitnami/postgresql
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: bitfly_pgdata
