version: '3.0'

services:

  pg:
    container_name: bitfly_db
    image: bitnami/postgresql
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  api:
    container_name: bitfly_api
    image: eliezercastro/bit-fly.co:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - pg
    networks:
      - default

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    volumes: ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    mem_limit: 512m
    networks:
      - default

volumes:
  pgdata: {}

networks:
  default:


